### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by pavan541cs**

### CODE REVIEW

**Comment by pavan541cs** [comment]
@eeliu wrong version in go.mod file and this is cause errors on dependency download.

**Review by eeliu — APPROVED** [review]
LGTM

**Comment by eeliu** [comment]
@pavan541cs  Thanks

**Comment by pavan541cs** [comment]
@eeliu When can I expect the release. Waiting for integrating with my golang application

**Comment by eeliu** [comment]
@pavan541cs 
Got it

**Comment by eeliu** [comment]
> @eeliu When can I expect the release. Waiting for integrating with my golang application

Please check https://github.com/pinpoint-apm/go-aop-agent/releases/tag/v1.0.1. 
If you found problem, post an issue to us without any hesitation!

**Pull request merged**
